# NumPy Practice Workbook

## Instructions

- Attempt all questions.
- Do not modify the question text.
- Write your solution only in the code cell provided below each question.
- Do not refer to external solutions.
- Test your code before moving to the next question.


## About This Notebook

<details>
<summary><b>Click to expand: What this notebook contains</b></summary>

This is a 50-question NumPy practice workbook designed for data analytics learners.

**Topics covered:**
- Array creation (`np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.diag`)
- Array attributes (`shape`, `size`, `ndim`, `dtype`)
- Random number generation (`randint`, `randn`, `normal`, `uniform`, `choice`, `shuffle`)
- Indexing and slicing (1-D, 2-D, and 3-D arrays)
- Element-wise arithmetic and scalar operations
- Manual reshaping, flattening, and diagonal extraction using loops
- `np.mgrid` for grid generation
- A final mini data-simulation pipeline that combines these concepts

**How it is organized:**
- Each question is in its own markdown cell, followed by a code cell for the solution
- A hint is provided under every question
- Run the cells in order from top to bottom to see the outputs

</details>


## Question 1

Import NumPy using its standard alias and print the NumPy version.

**Hint:**  
The version string is stored as an attribute of the NumPy module.


In [1]:
# Write your solution here
import numpy as np

## Question 2

Create a 1-D NumPy array containing the integers from 10 to 15 and print it. Also print its data type using `type()`.

**Hint:**  
Use `np.array()`.


In [2]:
# Write your solution here
import numpy as np

arr = np.array([10, 11, 12, 13, 14, 15])
print(arr)

# type() returns the type of the object.
print(type(arr))

[10 11 12 13 14 15]
<class 'numpy.ndarray'>


## Question 3

Create a 1-D NumPy array of five float values. Print the array and then print its `dtype`, `ndim`, `size`, and `shape` attributes.

**Hint:**  
Each of these is an attribute of the array object.


In [3]:
# Write your solution here
import numpy as np

arr = np.array([10.5, 20.8, 30.2, 40.6, 50.1])
print(arr)

# dtype returns the data type of the array elements.
print(arr.dtype)

# ndim returns the number of dimensions of the array.
print(arr.ndim)

# size returns the total number of elements in the array.
print(arr.size)

# shape returns the shape (rows, columns) of the array.
print(arr.shape)

[10.5 20.8 30.2 40.6 50.1]
float64
1
5
(5,)


## Question 4

Create a 2-D NumPy array with two rows and four columns using integer values of your choice. Print the array and confirm its shape.

**Hint:**  
Pass a list of lists to `np.array()`.


In [4]:
# Write your solution here
import numpy as np

# Create a 2-D array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])
print(arr)

# Print the shape of the array.
print(arr.shape)

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)


## Question 5

Create a 3-D NumPy array with shape `(2, 2, 3)`. Print the array and verify its `ndim` and `size`.

**Hint:**  
Think about how many lists need to be nested inside each other.


In [5]:
# Write your solution here
import numpy as np

#3-D NumPy array with shape (2, 2, 3)
arr = np.array([[[1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]]])

#print array
print(arr)

#Print the array and verify its ndim
print(arr.ndim)

#Print the array and verify its size
print(arr.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3
12


## Question 6

Use `np.arange()` to generate an array of integers starting from 3, ending before 20, with a step of 3. Print the result.

**Hint:**  
Use the start, stop, and step parameters of `np.arange()`.


In [6]:
# Write your solution here
import numpy as np

# Create an array from 3 to 20 with a step of 3.
arr = np.arange(3, 20, 3)
print(arr)

[ 3  6  9 12 15 18]


## Question 7

Use `np.linspace()` to generate 8 equally spaced values between 0 and 1 (inclusive). Print the result.

**Hint:**  
The third argument controls the number of points.


In [7]:
# Write your solution here
import numpy as np

# Generate 8 equally spaced values between 0 and 1.
arr = np.linspace(0, 1, 8)
print(arr)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


## Question 8

Use `np.zeros()` to create a 4×4 matrix filled with zeros. Then use `np.ones()` to create a 3×2 matrix filled with ones. Print both.

**Hint:**  
Pass a tuple for the shape argument.


In [8]:
# Create a 4×4 matrix filled with zeros.
arr1 = np.zeros((4,4))
print(arr1)

print()

# Create a 3×2 matrix filled with ones.
arr2 = np.ones((3,2))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Question 9

Convert the tuple `(5, 10, 15, 20)` into a NumPy array with `dtype=float` using `np.asarray()`. Print the result and confirm the dtype.

**Hint:**  
Use `np.asarray()` with the `dtype` parameter.


In [9]:
# Convert a tuple into a NumPy array with float data type.
arr = np.asarray((5, 10, 15, 20), dtype=float)
print(arr)

# Print the data type of the array elements.
print(arr.dtype)

[ 5. 10. 15. 20.]
float64


## Question 10

Create a diagonal matrix from the list `[2, 4, 6, 8]` using `np.diag()`. Print the resulting matrix and its shape.

**Hint:**  
Use `np.diag()` with a list of values.


In [10]:
# Create a diagonal matrix from the given list.
arr = np.diag([2, 4, 6, 8])
print(arr)

# Print the shape of the matrix.
print(arr.shape)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
(4, 4)


## Question 11

Using `np.random.randint()`, generate a 3×3 array of random integers between 1 and 50. Print the array.

**Hint:**  
The third argument to `np.random.randint()` controls the shape.


In [11]:
# Generate a 3×3 array of random integers between 1 and 50.
arr = np.random.randint(1, 51, (3,3))
print(arr)

[[35 16 26]
 [ 8 19 38]
 [ 3  6 32]]


## Question 12

Using `np.random.random()`, generate a 2×4 array of random floats between 0 and 1. Print the array.

**Hint:**  
Pass a shape tuple to `np.random.random()`.


In [12]:
arr = np.random.random((2,4))
print(arr)

[[0.3854007  0.42978026 0.01688066 0.10909595]
 [0.4240275  0.18757653 0.66375159 0.35394252]]


## Question 13

Create a NumPy array `arr = np.array([10, 20, 30, 40, 50, 60])`. Access and print the first element, the last element, and the element at index 3.

**Hint:**  
Use positive integer indexing.


In [13]:
# Create a NumPy array.
arr = np.array([10, 20, 30, 40, 50, 60])

# Print the first element.
print(arr[0])

# Print the last element.
print(arr[-1])

# Print the element at index 3.
print(arr[3])

10
60
40


## Question 14

Create the following 2-D array:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
Access and print: the element at row 1 column 2, the entire second row, and the entire first column.

**Hint:**  
Use `array[row, col]` notation for 2-D indexing.


In [14]:
# Create a 2-D array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Print the element at row 1, column 2.
print(arr[1,2])

# Print the entire second row.
print(arr[1,:])

# Print the entire first column.
print(arr[:,0])

6
[4 5 6]
[1 4 7]


## Question 15

Create a 1-D array using `np.arange(1, 11)`. Perform the following scalar operations and print each result:
- Add 5 to every element
- Multiply every element by 3
- Subtract 2 from every element

**Hint:**  
Scalar operations in NumPy are applied element-wise automatically.


In [15]:
# Create a 1-D array.
arr = np.arange(1, 11)
print(arr)

print()

# Add 5 to every element.
print(arr + 5)

print()

# Multiply every element by 3.
print(arr * 3)

print()

# Subtract 2 from every element.
print(arr - 2)

[ 1  2  3  4  5  6  7  8  9 10]

[ 6  7  8  9 10 11 12 13 14 15]

[ 3  6  9 12 15 18 21 24 27 30]

[-1  0  1  2  3  4  5  6  7  8]


## Question 16

Create a 2-D array with values:
```
[[10, 20, 30],
 [40, 50, 60]]
```
Print `ndim`, `shape`, `size`, and `dtype` for this array.

**Hint:**  
These are all attributes of the NumPy ndarray object.


In [16]:
# Create a 2-D array.
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# Print the array.
print(arr)

# Print the number of dimensions.
print(arr.ndim)

# Print the shape of the array.
print(arr.shape)

# Print the total number of elements.
print(arr.size)

# Print the data type of the array elements.
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
2
(2, 3)
6
int64


## Question 17

Explain the key difference between a Python list and a NumPy array by creating one of each containing mixed data types (integers, a string, a float, and a complex number). Print both and observe the output.

**Hint:**  
Arrays enforce a single dtype; lists do not.


In [17]:
# Create a Python list with mixed data types.
list1 = [10, "Python", 20.5, 3+4j]
print(list1)

print()

# Create a NumPy array with mixed data types.
arr = np.array([10, "Python", 20.5, 3+4j])
print(arr)

# Print the data type of the NumPy array.
print(arr.dtype)

[10, 'Python', 20.5, (3+4j)]

['10' 'Python' '20.5' '(3+4j)']
<U64


## Question 18

Use `np.logspace()` to generate 6 values between 10^0 and 10^4 with base 10. Print the result.

**Hint:**  
Use the `base` parameter of `np.logspace()`.


In [18]:
# Generate 6 values between 10^0 and 10^4 with base 10.
arr = np.logspace(0,4,6, base = 10)
print(arr)

[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]


## Question 19

Create a diagonal matrix using `np.diag([3, 6, 9])` with an offset of `k=1` (super-diagonal). Then create another with `k=-1` (sub-diagonal). Print both and note the shapes.

**Hint:**  
The `k` parameter in `np.diag()` shifts the diagonal position.


In [19]:
arr = np.diag([3,6,9], k=1)
print(arr)

[[0 3 0 0]
 [0 0 6 0]
 [0 0 0 9]
 [0 0 0 0]]


## Question 20

Use `np.mgrid` to generate a 2-D grid for rows `0:4` and columns `0:3`. Print both the row grid and the column grid separately.

**Hint:**  
Unpack the result of `np.mgrid` into two variables.


In [20]:
# Generate row and column grids.
row_grid, col_grid = np.mgrid[0:4, 0:3]

# Print the row grid.
print(row_grid)

print()

# Print the column grid.
print(col_grid)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


## Question 21

Create the 4×4 matrix:
```
M = [[1,2,3,8],[4,5,6,1],[7,8,9,2],[3,4,5,7]]
```
Then print:
- Row at index 2 in reverse order
- The first two rows entirely
- Column at index 1 for rows 0 to 2

**Hint:**  
Use slicing with `[::-1]` and `:` for row/column selection.


In [21]:
# Create a 4×4 matrix.
M = np.array([[1, 2, 3, 8],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [3, 4, 5, 7]])

# Print row at index 2 in reverse order.
print(M[2, ::-1])

print()

# Print the first two rows.
print(M[:2, :])

print()

# Print column at index 1 for rows 0 to 2.
print(M[0:3, 1])

[2 9 8 7]

[[1 2 3 8]
 [4 5 6 1]]

[2 5 8]


## Question 22

Create a 2-D array of shape (3, 4) using `np.random.randint()` with values between 10 and 99. Perform element-wise multiplication of the array with itself and print the result.

**Hint:**  
Element-wise multiplication uses the `*` operator.


In [22]:
# Create a 2-D array of shape (3,4) with random integers between 10 and 99.
arr = np.random.randint(10, 100, (3,4))
print(arr)

print()

# Perform element-wise multiplication.
print(arr * arr)

[[15 49 97 54]
 [19 28 98 98]
 [44 79 47 45]]

[[ 225 2401 9409 2916]
 [ 361  784 9604 9604]
 [1936 6241 2209 2025]]


## Question 23

Using `np.random.randn()`, generate a 3×4 array from the standard normal distribution (mean=0, std=1). Print the array.

**Hint:**  
Use `np.random.randn()` with row and column counts as separate arguments.


In [23]:
# Generate a 3x4 array from the standard normal distribution.
arr = np.random.randn(3, 4)
print(arr)


[[-0.5382011   1.61809087 -0.0124115  -1.86134244]
 [-1.6337002   1.53196922 -0.26173338 -0.75480615]
 [ 0.00859317 -1.28361596  2.04906568 -0.70756064]]


## Question 24

Using `np.random.normal()`, generate a 2×5 array with a mean of 50 and a standard deviation of 10. Print the array.

**Hint:**  
The three parameters are loc (mean), scale (std), and size (shape).


In [24]:
# Generate a 2x5 array with mean 50 and standard deviation 10.
arr = np.random.normal(50, 10, (2, 5))
print(arr)


[[52.70073264 47.21299505 62.89699077 39.68484317 31.34899069]
 [56.29278378 37.44300186 52.23726208 45.26514872 59.53187328]]


## Question 25

Using `np.random.uniform()`, generate a 3×3 array with values uniformly distributed between 5 and 25. Print the array.

**Hint:**  
Pass low, high, and size to `np.random.uniform()`.


In [25]:
# Generate a 3x3 array with values uniformly distributed between 5 and 25.
arr = np.random.uniform(5, 25, (3, 3))
print(arr)


[[13.41652608 12.72520065  5.95684194]
 [ 5.48986881  7.56413618 24.34280839]
 [15.7517165  15.22833226 21.5489257 ]]


## Question 26

Create a list `['Python', 'NumPy', 'Pandas', 'Matplotlib']` and use `np.random.choice()` to randomly select 5 elements from it (with replacement). Print the result.

**Hint:**  
Use `np.random.choice()` with your list and a count.


In [26]:
# Create the list of items.
items = ['Python', 'NumPy', 'Pandas', 'Matplotlib']

# Randomly select 5 elements with replacement.
choice = np.random.choice(items, 5)
print(choice)


['NumPy' 'Python' 'NumPy' 'Pandas' 'NumPy']


## Question 27

Create a 1-D array `np.array([7, 3, 1, 9, 5, 2, 8, 4, 6])` and use `np.random.shuffle()` to shuffle it in place. Print the array before and after shuffling.

**Hint:**  
Note that `np.random.shuffle()` modifies the array in place and returns `None`.


In [27]:
# Create a 1-D array.
arr = np.array([7, 3, 1, 9, 5, 2, 8, 4, 6])
print("Before shuffling:", arr)

# Shuffle the array in place.
np.random.shuffle(arr)
print("After shuffling: ", arr)


Before shuffling: [7 3 1 9 5 2 8 4 6]
After shuffling:  [9 3 7 1 4 2 5 6 8]


## Question 28

Create a 3-D array with shape `(2, 3, 4)` using values of your choice. Then:
- Access and print the element at position `[1][0][2]`
- Access and print the sub-array at `[0][1]`

**Hint:**  
Use chained index notation `arr[x][y][z]` or `arr[x, y, z]`.


In [28]:
# Create a 3-D array with shape (2, 3, 4).
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)

print()

# Access the element at position [1][0][2].
print(arr[1][0][2])

print()

# Access the sub-array at [0][1].
print(arr[0][1])


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

15

[5 6 7 8]


## Question 29

Create a 3-D array of shape `(3, 2, 3)` and flatten it to a 1-D array using a loop (without using `.flatten()` or `.reshape()`). Print the original and the resulting 1-D array.

**Hint:**  
Use a triple nested loop and `append()` to collect elements.


In [29]:
# Create a 3-D array of shape (3, 2, 3).
arr = np.arange(1, 19).reshape(3, 2, 3)
print(arr)

print()

# Flatten it to a 1-D array using a triple nested loop.
flat = []
for block in arr:
    for row in block:
        for value in row:
            flat.append(value)

flat = np.array(flat)
print(flat)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


## Question 30

Use `np.asarray()` to convert a tuple of tuples `((1,2,3),(4,5,6))` into a 2-D NumPy array with `dtype=float`. Print the result and its shape.

**Hint:**  
Pass the nested tuple directly to `np.asarray()`.


In [30]:
# Convert a tuple of tuples into a 2-D array with dtype=float.
arr = np.asarray(((1, 2, 3), (4, 5, 6)), dtype=float)
print(arr)

# Print the shape of the array.
print(arr.shape)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


## Question 31

Create a 3-D array of shape `(3, 2, 3)` and extract the last element of every inner sub-array using nested loops. Print all extracted values on a single line.

**Hint:**  
Iterate over the outer dimensions and use index `[2]` for the last position.


In [31]:
# Create a 3-D array of shape (3, 2, 3).
arr = np.arange(1, 19).reshape(3, 2, 3)
print(arr)

print()

# Extract the last element of every inner sub-array using nested loops.
last_elements = []
for block in arr:
    for row in block:
        last_elements.append(row[-1])

print(last_elements)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[np.int64(3), np.int64(6), np.int64(9), np.int64(12), np.int64(15), np.int64(18)]


## Question 32

Create a 4×4 integer array using `np.random.randint()`. Then:
- Print the row at index 1 with elements from index 0 to 2
- Print the row at index 3 in reverse
- Print the column at index 2 for all rows in reverse order

**Hint:**  
Combine row and column slicing with `[::-1]` for reversal.


In [32]:
# Create a 4x4 integer array.
arr = np.random.randint(1, 50, (4, 4))
print(arr)

print()

# Print the row at index 1 with elements from index 0 to 2.
print(arr[1, 0:3])

print()

# Print the row at index 3 in reverse.
print(arr[3, ::-1])

print()

# Print the column at index 2 for all rows in reverse order.
print(arr[::-1, 2])


[[30 39 35 41]
 [19 45 48  2]
 [12 34 45  5]
 [33 31 34 35]]

[19 45 48]

[35 34 31 33]

[34 45 48 35]


## Question 33

Create two arrays: `a = np.arange(1, 7)` and `b = np.arange(7, 13)`. Perform element-wise addition, subtraction, and multiplication. Print each result.

**Hint:**  
NumPy applies arithmetic operators element-wise on arrays of the same shape.


In [33]:
# Create two arrays.
a = np.arange(1, 7)
b = np.arange(7, 13)

# Element-wise addition.
print(a + b)

print()

# Element-wise subtraction.
print(a - b)

print()

# Element-wise multiplication.
print(a * b)


[ 8 10 12 14 16 18]

[-6 -6 -6 -6 -6 -6]

[ 7 16 27 40 55 72]


## Question 34

Generate an array using `np.linspace(1, 100, 20)`. Then subtract the scalar value `10` from the entire array and multiply the result by `2`. Print the final array.

**Hint:**  
Scalar operations chain naturally in NumPy.


In [34]:
# Generate an array using linspace.
arr = np.linspace(1, 100, 20)

# Subtract 10 from the entire array and multiply the result by 2.
result = (arr - 10) * 2
print(result)


[-18.          -7.57894737   2.84210526  13.26315789  23.68421053
  34.10526316  44.52631579  54.94736842  65.36842105  75.78947368
  86.21052632  96.63157895 107.05263158 117.47368421 127.89473684
 138.31578947 148.73684211 159.15789474 169.57894737 180.        ]


## Question 35

Create a 2-D array using `np.random.randint(1, 20, (4, 4))`. Print:
- The full array
- Its shape, size, ndim, and dtype
- Only the upper-left 2×2 block using slicing

**Hint:**  
Use `array[0:2, 0:2]` for the upper-left block.


In [35]:
# Create a 2-D array.
arr = np.random.randint(1, 20, (4, 4))

# Print the full array.
print(arr)

print()

# Print shape, size, ndim, and dtype.
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

print()

# Print only the upper-left 2x2 block.
print(arr[0:2, 0:2])


[[11 17 15 17]
 [ 2  8 14 16]
 [19  8 15 18]
 [19  4  9 11]]

(4, 4)
16
2
int64

[[11 17]
 [ 2  8]]


## Question 36

Create a 3-D array of shape `(2, 3, 4)` using `np.random.randint(1, 100, (2, 3, 4))`. Manually flatten it to a 1-D array using list comprehension (three levels of nesting). Verify the result has 24 elements.

**Hint:**  
Use `[z for x in arr for y in x for z in y]` and wrap with `np.array()`.


In [36]:
# Create a 3-D array of shape (2, 3, 4).
arr = np.random.randint(1, 100, (2, 3, 4))
print(arr)

print()

# Manually flatten it using list comprehension (three levels of nesting).
flat = np.array([z for x in arr for y in x for z in y])
print(flat)

# Verify the result has 24 elements.
print(flat.size)


[[[ 9 32 27  6]
  [27 17 86 20]
  [58 17 71 25]]

 [[98 20 15 21]
  [33 78 22 26]
  [90 43 52 53]]]

[ 9 32 27  6 27 17 86 20 58 17 71 25 98 20 15 21 33 78 22 26 90 43 52 53]
24


## Question 37

Create two separate 3×3 matrices using `np.random.randint()`. Perform element-wise multiplication of the two matrices and subtract a scalar of 5 from the result. Print the final matrix.

**Hint:**  
Combine the `*` operator and scalar subtraction in sequence.


In [37]:
# Create two separate 3x3 matrices.
m1 = np.random.randint(1, 20, (3, 3))
m2 = np.random.randint(1, 20, (3, 3))

print(m1)
print()
print(m2)

print()

# Element-wise multiplication and subtract a scalar of 5.
result = (m1 * m2) - 5
print(result)


[[10  2  8]
 [ 1  1  4]
 [10  5 13]]

[[17 15  6]
 [14  9  6]
 [ 4 19  4]]

[[165  25  43]
 [  9   4  19]
 [ 35  90  47]]


## Question 38

Using `np.diag()`, create three diagonal matrices:
- A 3×3 using values `[1, 2, 3]` on the main diagonal
- A 4×4 using values `[1, 2, 3, 4]` on the super-diagonal (`k=1`)
- A 4×4 using values `[1, 2, 3, 4]` on the sub-diagonal (`k=-1`)

Print all three and confirm their shapes.

**Hint:**  
The `k` parameter offsets the diagonal; shape increases by 1 when `k != 0`.


In [38]:
# 3x3 diagonal matrix using values on the main diagonal.
d1 = np.diag([1, 2, 3])
print(d1)
print(d1.shape)

print()

# 4x4 diagonal matrix on the super-diagonal (k=1).
d2 = np.diag([1, 2, 3, 4], k=1)
print(d2)
print(d2.shape)

print()

# 4x4 diagonal matrix on the sub-diagonal (k=-1).
d3 = np.diag([1, 2, 3, 4], k=-1)
print(d3)
print(d3.shape)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
(5, 5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
(5, 5)


## Question 39

Generate a 2-D array of shape (5, 5) using `np.random.uniform(0, 1, (5, 5))`. Then:
- Print the entire array
- Extract and print only the main diagonal values using `np.diag()` on the result

**Hint:**  
Calling `np.diag()` on a 2-D array extracts the diagonal elements.


In [39]:
# Generate a 2-D array of shape (5, 5).
arr = np.random.uniform(0, 1, (5, 5))
print(arr)

print()

# Extract and print only the main diagonal values.
print(np.diag(arr))


[[0.20976107 0.93524634 0.57505406 0.68436537 0.08080955]
 [0.08660048 0.15164733 0.43448781 0.45819239 0.55716659]
 [0.38026944 0.83291877 0.33933512 0.80061093 0.84457465]
 [0.14563474 0.21317392 0.96737056 0.92165852 0.34564541]
 [0.15361817 0.56692055 0.33651339 0.0818482  0.64833526]]

[0.20976107 0.15164733 0.33933512 0.92165852 0.64833526]


## Question 40

Create a 5×5 integer array using `np.random.randint(10, 99, (5, 5))`. Demonstrate five different slicing operations:
1. First row
2. Last column
3. Every other row
4. The bottom-right 2×2 sub-matrix
5. The full array in reverse row order

**Hint:**  
Use combinations of `[::-1]`, `[start:stop:step]`, and row-column slicing.


In [40]:
# Create a 5x5 integer array.
arr = np.random.randint(10, 99, (5, 5))
print(arr)

print()

# First row.
print(arr[0, :])

print()

# Last column.
print(arr[:, -1])

print()

# Every other row.
print(arr[::2, :])

print()

# Bottom-right 2x2 sub-matrix.
print(arr[-2:, -2:])

print()

# Full array in reverse row order.
print(arr[::-1, :])


[[45 47 63 59 20]
 [71 25 85 50 50]
 [57 31 47 33 31]
 [54 90 97 57 33]
 [80 94 33 38 14]]

[45 47 63 59 20]

[20 50 31 33 14]

[[45 47 63 59 20]
 [57 31 47 33 31]
 [80 94 33 38 14]]

[[57 33]
 [38 14]]

[[80 94 33 38 14]
 [54 90 97 57 33]
 [57 31 47 33 31]
 [71 25 85 50 50]
 [45 47 63 59 20]]


## Question 41

Using `np.random.choice()`, simulate 20 coin flips from the list `['H', 'T']`. Count manually (using a loop) how many times each outcome appears and print the counts.

**Hint:**  
Iterate through the result array and maintain a count variable for each outcome.


In [41]:
# Simulate 20 coin flips.
flips = np.random.choice(['H', 'T'], 20)
print(flips)

print()

# Count manually using a loop.
heads = 0
tails = 0
for flip in flips:
    if flip == 'H':
        heads += 1
    else:
        tails += 1

print("Heads:", heads)
print("Tails:", tails)


['T' 'H' 'T' 'H' 'H' 'T' 'H' 'H' 'H' 'H' 'H' 'T' 'T' 'T' 'T' 'T' 'T' 'T'
 'H' 'H']

Heads: 10
Tails: 10


## Question 42

Create a 4×4 array using `np.random.normal(50, 15, (4, 4))`. Then:
- Subtract the scalar 50 from every element
- Divide every element of the result by 15
- Print the final array (this simulates Z-score normalization)

**Hint:**  
Chain scalar subtraction and division using standard operators.


In [42]:
# Create a 4x4 array from a normal distribution.
arr = np.random.normal(50, 15, (4, 4))
print(arr)

print()

# Subtract 50 from every element and divide the result by 15.
z_scores = (arr - 50) / 15
print(z_scores)


[[55.94114251 30.50338435 69.74665041 48.46450651]
 [66.4693856  64.62323159 33.40626266 37.98240649]
 [45.04182277 51.13222209 31.88757466 30.96474354]
 [38.25382145 55.34361627 50.91376178 66.09436762]]

[[ 0.39607617 -1.29977438  1.31644336 -0.10236623]
 [ 1.09795904  0.97488211 -1.10624916 -0.8011729 ]
 [-0.33054515  0.07548147 -1.20749502 -1.2690171 ]
 [-0.78307857  0.35624108  0.06091745  1.07295784]]


## Question 43

Create a 1-D array using `np.arange(1, 25)`. Reshape it manually (do not use `.reshape()`) into a 3-D structure by slicing it into a nested list and converting back with `np.array()`. The final shape should be `(2, 3, 4)`.

**Hint:**  
Slice the flat array into segments and nest them into lists of the right dimensions.


In [43]:
# Create a 1-D array.
flat = np.arange(1, 25)
print(flat)

print()

# Manually reshape into a 3-D structure of shape (2, 3, 4).
nested = []
for i in range(2):
    block = []
    for j in range(3):
        start = (i * 12) + (j * 4)
        block.append(list(flat[start:start + 4]))
    nested.append(block)

arr_3d = np.array(nested)
print(arr_3d)
print(arr_3d.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


## Question 44

Using only `np.zeros()`, `np.ones()`, and scalar operations, create a 4×4 identity-like matrix where diagonal positions hold the value `5` and all other positions hold `0`. Print the matrix.

*(Do not use `np.eye()` or `np.diag()`.)*

**Hint:**  
Think about how to isolate diagonal positions using `np.ones()` and multiplication.


In [44]:
# Start with a 4x4 matrix of zeros and a 4x4 matrix of ones.
zeros_mat = np.zeros((4, 4))
ones_mat = np.ones((4, 4))

# Build the diagonal matrix using scalar operations and indexing.
mat = zeros_mat.copy()
for i in range(4):
    mat[i, i] = ones_mat[i, i] * 5

print(mat)


[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


## Question 45

Generate a 1-D array of 30 random integers between 1 and 10 using `np.random.randint()`. Without using any built-in NumPy statistical function, use a loop to manually compute:
- The sum of all elements
- The minimum value
- The maximum value

Print all three.

**Hint:**  
Iterate through the array and maintain running totals and comparisons.


In [45]:
# Generate a 1-D array of 30 random integers between 1 and 10.
arr = np.random.randint(1, 11, 30)
print(arr)

print()

# Manually compute sum, minimum, and maximum using a loop.
total = 0
minimum = arr[0]
maximum = arr[0]

for value in arr:
    total += value
    if value < minimum:
        minimum = value
    if value > maximum:
        maximum = value

print("Sum:", total)
print("Min:", minimum)
print("Max:", maximum)


[ 8 10  7  6  6  7  8 10  2  9  8  3  1  8  1  1  1 10  5  8  1  4  9  6
  5  1  4  2  3  3]

Sum: 157
Min: 1
Max: 10


## Question 46

Use `np.mgrid` to create a 2-D grid for `x` in range `0:5` and `y` in range `0:5`. Compute a new array where each element equals `x + y` using the two grid arrays. Print the resulting 5×5 array.

**Hint:**  
Unpack the mgrid result into x and y, then add them together.


In [46]:
# Create a 2-D grid for x and y in range 0:5.
x, y = np.mgrid[0:5, 0:5]

# Compute a new array where each element equals x + y.
result = x + y
print(result)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


## Question 47

Create a 3-D array of shape `(4, 3, 3)` using `np.random.randint(1, 50, (4, 3, 3))`. For each of the 4 blocks (first dimension), extract only its diagonal elements and print them.

**Hint:**  
Use a loop over the first dimension and `np.diag()` on each 2-D slice.


In [47]:
# Create a 3-D array of shape (4, 3, 3).
arr = np.random.randint(1, 50, (4, 3, 3))
print(arr)

print()

# For each of the 4 blocks, extract only its diagonal elements.
for i, block in enumerate(arr):
    print("Block", i, "diagonal:", np.diag(block))


[[[39 28 21]
  [25 26 32]
  [22 30 48]]

 [[44 23 25]
  [41 40 48]
  [11 40  6]]

 [[44 15  2]
  [46 27 21]
  [16 21 14]]

 [[46  5 47]
  [26  5 26]
  [27 45 14]]]

Block 0 diagonal: [39 26 48]
Block 1 diagonal: [44 40  6]
Block 2 diagonal: [44 27 14]
Block 3 diagonal: [46  5 14]


## Question 48

Create a 6×6 matrix using `np.arange(1, 37).reshape(6, 6)` — but since you have not used `.reshape()`, do it manually by slicing `np.arange(1, 37)` into 6 segments of 6 and stacking them. Then:
- Print only the border elements (first row, last row, first column, last column)
- Print only the inner 4×4 sub-matrix

**Hint:**  
Slice rows and columns independently to isolate the border and inner sections.


In [48]:
# Manually build a 6x6 matrix by slicing arange(1, 37) into 6 segments.
flat = np.arange(1, 37)
rows = [flat[i * 6:(i + 1) * 6] for i in range(6)]
matrix = np.array(rows)
print(matrix)

print()

# Print only the border elements.
print("First row:", matrix[0, :])
print("Last row:", matrix[-1, :])
print("First column:", matrix[:, 0])
print("Last column:", matrix[:, -1])

print()

# Print only the inner 4x4 sub-matrix.
print(matrix[1:5, 1:5])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]



First row: [1 2 3 4 5 6]
Last row: [31 32 33 34 35 36]
First column: [ 1  7 13 19 25 31]
Last column: [ 6 12 18 24 30 36]

[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


## Question 49

Using `np.random.shuffle()`, demonstrate that shuffle modifies the array in place:
1. Create an array `a = np.arange(1, 11)`
2. Assign `b = a` (not a copy)
3. Shuffle `a`
4. Print both `a` and `b` and explain why both changed

Then repeat using a proper copy (using `list()` or slicing) so that the original is preserved.

**Hint:**  
Assignment in NumPy creates a reference, not a copy. Use `a.copy()` or `list(a)` for a true copy.


In [49]:
# Create an array.
a = np.arange(1, 11)

# Assign b = a (not a copy).
b = a

# Shuffle a.
np.random.shuffle(a)

# Both a and b changed because b references the same array as a.
print("a:", a)
print("b:", b)

print()

# Repeat using a proper copy.
c = np.arange(1, 11)
d = c.copy()

np.random.shuffle(c)

# Only c changed because d is an independent copy.
print("c:", c)
print("d:", d)


a: [ 5 10  9  3  4  7  6  1  8  2]
b: [ 5 10  9  3  4  7  6  1  8  2]

c: [ 7 10  9  6  3  2  8  5  1  4]
d: [ 1  2  3  4  5  6  7  8  9 10]


## Question 50

Build a mini data simulation pipeline using only the NumPy concepts from this course:
1. Use `np.random.normal(70, 10, (5, 6))` to generate a 5×6 marks matrix (5 students, 6 subjects)
2. Subtract 70 from every element (center around 0)
3. Divide every element by 10 (scale)
4. Use a nested loop to print each student's row with their original subject marks
5. Also print the shape, size, ndim, and dtype of the original matrix

**Hint:**  
Combine random generation, scalar operations, array attributes, and looping over 2-D arrays.


In [50]:
# Generate a 5x6 marks matrix (5 students, 6 subjects).
marks = np.random.normal(70, 10, (5, 6))

# Subtract 70 from every element (center around 0).
centered = marks - 70

# Divide every element by 10 (scale).
scaled = centered / 10

print(scaled)

print()

# Print each student's row with their original subject marks.
for i, row in enumerate(marks):
    print("Student", i + 1, ":", row)

print()

# Print the shape, size, ndim, and dtype of the original matrix.
print(marks.shape)
print(marks.size)
print(marks.ndim)
print(marks.dtype)


[[ 0.42057798  0.66908111  0.28726343 -0.15377367 -0.29948814  0.75424755]
 [-1.1660671  -0.95229747 -1.04322139 -0.87874537 -1.24061663  0.04481364]
 [-0.84089386  0.95841055 -1.81848465  0.11821494 -0.2869626   0.11601838]
 [ 0.32078291 -0.47504459 -1.52813147 -0.75470017 -0.79512251 -0.17553129]
 [-0.64160359 -1.32589506  0.40324765 -1.29887371  0.51410116  2.09797817]]

Student 1 : [74.20577979 76.69081108 72.87263434 68.4622633  67.00511862 77.54247548]
Student 2 : [58.33932901 60.47702531 59.56778614 61.21254628 57.59383365 70.44813637]
Student 3 : [61.59106141 79.58410552 51.81515348 71.18214938 67.13037398 71.16018384]
Student 4 : [73.20782915 65.24955412 54.71868533 62.45299829 62.04877491 68.24468713]
Student 5 : [63.58396412 56.74104939 74.0324765  57.0112629  75.14101161 90.97978166]

(5, 6)
30
2
float64


# Congratulations!

You have completed all 50 NumPy programming exercises.

Review your solutions, optimize your code where possible, and discuss different approaches with your instructor.
